/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurantmanagement;

import javax.swing.JFrame;
import javax.swing.JOptionPane;




/**
 *
 * @author arsen
 */
public class LoyaltyAppGUI extends javax.swing.JFrame {


    private int customerId;
    private Order order;
    private Customer currentCustomer;

    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoyaltyAppGUI.class.getName());
    
    public LoyaltyAppGUI(int customerId) {
    this.customerId = customerId;
    initComponents();
       setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    
    // Initialize labels as hidden
    reward_area.setVisible(false);
    ID_label.setVisible(false);
    name_label.setVisible(false);
    phone_label.setVisible(false);
    address_label.setVisible(false);
    totalSpent_label.setVisible(false);
    points_label.setVisible(false);
    orders_label.setVisible(false);
    
  
    order = new Order(); 
    
    currentCustomer = Customer.getCustomerById(customerId);
    
    if (currentCustomer == null) {
        JOptionPane.showMessageDialog(this, "Customer not found with ID: " + customerId);
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prf_btn = new javax.swing.JButton();
        Rew_btn = new javax.swing.JButton();
        ID_label = new javax.swing.JLabel();
        name_label = new javax.swing.JLabel();
        phone_label = new javax.swing.JLabel();
        address_label = new javax.swing.JLabel();
        totalSpent_label = new javax.swing.JLabel();
        points_label = new javax.swing.JLabel();
        orders_label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reward_area = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        prf_btn.setText("Profile");
        prf_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        prf_btn.addActionListener(this::prf_btnActionPerformed);

        Rew_btn.setText("Rewards");
        Rew_btn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Rew_btn.addActionListener(this::Rew_btnActionPerformed);

        ID_label.setText("ID:");

        name_label.setText("Name:");

        phone_label.setText("Phone number:");

        address_label.setText("Address:");

        totalSpent_label.setText("Total Spent:");

        points_label.setText("Loyalty points:");

        orders_label.setText("Total Orders:");

        reward_area.setBackground(new java.awt.Color(242, 242, 242));
        reward_area.setColumns(20);
        reward_area.setRows(5);
        jScrollPane1.setViewportView(reward_area);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Rew_btn, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ID_label, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phone_label, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(address_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalSpent_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(points_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orders_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(prf_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prf_btn)
                    .addComponent(Rew_btn))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(ID_label)
                        .addGap(18, 18, 18)
                        .addComponent(name_label)
                        .addGap(18, 18, 18)
                        .addComponent(phone_label)
                        .addGap(20, 20, 20)
                        .addComponent(address_label))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(totalSpent_label)
                .addGap(18, 18, 18)
                .addComponent(points_label)
                .addGap(20, 20, 20)
                .addComponent(orders_label)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prf_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prf_btnActionPerformed
         if (currentCustomer == null) {
            JOptionPane.showMessageDialog(this, "No customer loaded!");
            return;
        }

        ID_label.setText("ID: " + currentCustomer.getCustID());
        name_label.setText("Name: " + currentCustomer.getName());
        phone_label.setText("Phone: " + currentCustomer.getPhoneNum());
        address_label.setText("Address: " + currentCustomer.getAddress());
        if (order.getTotalAmountByCustomerId(currentCustomer.getCustID()) < 0) {
            totalSpent_label.setText("Total Spent: " + 0);
        } else {
            totalSpent_label.setText("Total Spent: " + order.getTotalAmountByCustomerId(currentCustomer.getCustID()));
        }
        points_label.setText("Loyalty Points: " + currentCustomer.getLoyaltyPoints());
        orders_label.setText("Total Orders: " + Customer.countOrdersByCustomer(customerId));

        ID_label.setVisible(true);
        name_label.setVisible(true);
        phone_label.setVisible(true);
        address_label.setVisible(true);
        totalSpent_label.setVisible(true);
        points_label.setVisible(true);
        orders_label.setVisible(true);
        reward_area.setVisible(false);
    
    }//GEN-LAST:event_prf_btnActionPerformed

    private void Rew_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rew_btnActionPerformed
        ID_label.setVisible(false);
        name_label.setVisible(false);
        phone_label.setVisible(false);
        address_label.setVisible(false);
        totalSpent_label.setVisible(false);
        points_label.setVisible(false);
        orders_label.setVisible(false);
        reward_area.setVisible(true);
        String rewards = Customer.getRewardsByCustomerId(currentCustomer.getCustID());
        reward_area.setText(rewards);
        
    }//GEN-LAST:event_Rew_btnActionPerformed

    /**
     * @param args the command line arguments
     */
       public static void main(String args[]) {
        // Example: normally this is called from the registration GUI
        java.awt.EventQueue.invokeLater(() -> new LoyaltyAppGUI(1).setVisible(true));
    
       }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID_label;
    private javax.swing.JButton Rew_btn;
    private javax.swing.JLabel address_label;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name_label;
    private javax.swing.JLabel orders_label;
    private javax.swing.JLabel phone_label;
    private javax.swing.JLabel points_label;
    private javax.swing.JButton prf_btn;
    private javax.swing.JTextArea reward_area;
    private javax.swing.JLabel totalSpent_label;
    // End of variables declaration//GEN-END:variables
}
