/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurantmanagement;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.*;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.JFrame;

/**
 *
 * @author Deepfix
 */
public class ManageAdminJFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManageAdminJFrame.class.getName());

    /**
     * Creates new form ManageAdminJFrame
     */
    public ManageAdminJFrame() {
        initComponents();
        setLocationRelativeTo(null);
                setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn3 = new javax.swing.JButton();
        Btn4 = new javax.swing.JButton();
        Btn5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtPass = new javax.swing.JTextField();
        Btn1 = new javax.swing.JButton();
        Btn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Btn3.setText("Update");
        Btn3.addActionListener(this::Btn3ActionPerformed);

        Btn4.setText("Search");
        Btn4.addActionListener(this::Btn4ActionPerformed);

        Btn5.setText("List");
        Btn5.addActionListener(this::Btn5ActionPerformed);

        jLabel1.setText("ID:");

        jLabel2.setText("Name:");

        jLabel3.setText("Password:");

        txtID.addActionListener(this::txtIDActionPerformed);

        txtPass.addActionListener(this::txtPassActionPerformed);

        Btn1.setText("Add");
        Btn1.addActionListener(this::Btn1ActionPerformed);

        Btn2.setText("Delete");
        Btn2.addActionListener(this::Btn2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(27, 27, 27)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(12, 12, 12)
                                                                .addComponent(Btn1)
                                                                .addGap(31, 31, 31)
                                                                .addComponent(Btn2)
                                                                .addGap(37, 37, 37)
                                                                .addComponent(Btn3))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(jLabel3)
                                                                .addComponent(txtID)
                                                                .addComponent(jLabel1)
                                                                .addComponent(txtName)
                                                                .addComponent(txtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(93, 93, 93)
                                                .addComponent(Btn4)
                                                .addGap(44, 44, 44)
                                                .addComponent(Btn5)))
                                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(8, 8, 8)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Btn1)
                                        .addComponent(Btn2)
                                        .addComponent(Btn3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Btn4)
                                        .addComponent(Btn5))
                                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn3ActionPerformed
        try {
            int id = Integer.parseInt(txtID.getText());
            String name = txtName.getText();
            String pass = txtPass.getText();
            if (name.isEmpty() || pass.isEmpty() || (id + "").isEmpty()) {
                JOptionPane.showMessageDialog(this, "Empty field!");
            }
            int flag = JOptionPane.showConfirmDialog(this, "Do you want to update this admin ?", "Confirme delete", JOptionPane.YES_NO_OPTION);
            if (flag == JOptionPane.YES_OPTION) {
                if (admin.updateAdminInfo(id, name, pass)) {
                    JOptionPane.showMessageDialog(this, "admin updated successfully");
                } else {
                    JOptionPane.showMessageDialog(this, "admin not found!");
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void Btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn4ActionPerformed
        try {
            int id = Integer.parseInt(txtID.getText());
            if ((id + "").isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter emloyee ID", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                String returnedEmp = admin.searchAdmin(id);
                JOptionPane.showMessageDialog(this, returnedEmp);
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void Btn5ActionPerformed(java.awt.event.ActionEvent evt) {
        ArrayList<String> adminn = admin.listAdmin();
        StringBuilder s = new StringBuilder();
        for (String e : adminn) {
            s.append(e).append("\n");
        }
        JOptionPane.showMessageDialog(this, s.toString());
    }

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {
    }

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }

    private void Btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn1ActionPerformed
        try {
            int id = Integer.parseInt(txtID.getText());
            String name = txtName.getText();
            String pass = txtPass.getText();

            if (name.isEmpty() || pass.isEmpty() || (id + "").isEmpty() || name.matches(".*\\d.*")) {
                JOptionPane.showMessageDialog(this, "Please, fill all fields and enter valied information", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                admin.addAdmin(id, name, pass);
                JOptionPane.showMessageDialog(this, "admin added successfully");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error" + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);

        }
    }

    private void Btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn2ActionPerformed
        try {
            int id = Integer.parseInt(txtID.getText());

            if ((id + "").isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please, enter admin ID");
            }
            int flag = JOptionPane.showConfirmDialog(this, "Do you want to delete this admin ?", "Confirme delete", JOptionPane.YES_NO_OPTION);
            if (flag == JOptionPane.YES_OPTION) {

                boolean deleted = admin.deleteAdmin(id);
                if (deleted) {
                    JOptionPane.showMessageDialog(this, "admin deleted successfully");
                } else {
                    JOptionPane.showMessageDialog(this, "admin not found!");
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ManageAdminJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn1;
    private javax.swing.JButton Btn2;
    private javax.swing.JButton Btn3;
    private javax.swing.JButton Btn4;
    private javax.swing.JButton Btn5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPass;
    // End of variables declaration//GEN-END:variables

    private static class admin {

        private static boolean updateAdminInfo(int id, String newUsername, String newPass) {
            boolean flag = false;
            try {
                ArrayList<String> admins = readAdmins();
                try (BufferedWriter BW = new BufferedWriter(new FileWriter("admin.txt"))) {
                    for (String lineOfEmp : admins) {
                        String[] parts = lineOfEmp.split(",");
                        if (Integer.parseInt(parts[0]) == id) {
                            BW.write(id + "," + newUsername + "," + newPass);
                            BW.newLine();
                            flag = true;
                        } else {
                            BW.write(lineOfEmp);
                            BW.newLine();
                        }
                    }
                }
                return flag;

            } catch (IOException | NumberFormatException e) {
            }
            return false;
        }

        private static String searchAdmin(int id) {
            ArrayList<String> admins = readAdmins();

            for (String admin : admins) {
                String[] parts = admin.split(",");
                if (Integer.parseInt(parts[0]) == id) {
                    return "Employee Found - ID: " + parts[0] + ", Username: " + parts[1];

                } else {
                    return "Admin id not found.";

                }
            }
            return null;

        }

        private static ArrayList<String> listAdmin() {
            ArrayList<String> adminInfo = new ArrayList<>();
            ArrayList<String> admins = readAdmins();
            for (String admin : admins) {
                String[] parts = admin.split(",");
                if (parts.length >= 2) {
                    adminInfo.add("ID: " + parts[0] + ", Username: " + parts[1]);
                }
            }
            return adminInfo;
        }

        private static void addAdmin(int id, String username, String password) {
            String adminInfo = id + "," + username + "," + password;
            File file = new File("admin.txt");
            try {
                try (BufferedWriter BW = new BufferedWriter(new FileWriter(file, true))) {
                    BW.write(adminInfo);
                    BW.newLine();
                    BW.flush();
                }
            } catch (IOException ex) {
            }
        }

        private static boolean deleteAdmin(int id) {
            ArrayList<String> employees = readAdmins();
            boolean flag = false;
            try {
                try (BufferedWriter BW = new BufferedWriter(new FileWriter("admin.txt"));) {
                    for (String lineOfEmp : employees) {
                        String[] parts = lineOfEmp.split(",");
                        if (Integer.parseInt(parts[0]) == id) {
                            flag = true;
                        } else {
                            BW.write(lineOfEmp);
                            BW.newLine();
                        }
                    }
                }
            } catch (IOException ex) {

            }

            return flag;
        }

        private static ArrayList<String> readAdmins() {
            ArrayList<String> admins = new ArrayList<>();
            File file = new File("admin.txt");
            try {
                if (!file.exists()) {
                    file.createNewFile();
                    return admins;
                } else {
                    try (BufferedReader BR = new BufferedReader(new FileReader(file))) {
                        String line;
                        while ((line = BR.readLine()) != null) {
                            admins.add(line);
                        }
                    }  

                }
            } catch (FileNotFoundException e) {
                System.out.println("File not found: " + file + ", " + e.getMessage());
            } catch (IOException ex) {
                System.out.println("An I/O error occurred: " + ex.getMessage());
            }
            return admins;
        }

        public admin() {
        }
    }
}
