/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package restaurantmanagement;

import java.awt.HeadlessException;
import java.io.File;
import java.util.Scanner;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author PC
 */
public class Update_Employee_info extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Update_Employee_info.class.getName());

    /**
     * Creates new form Update_Employee_info
     */
    public Update_Employee_info() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        idlable = new javax.swing.JLabel();
        fid = new javax.swing.JTextField();
        namelable = new javax.swing.JLabel();
        fName = new javax.swing.JTextField();
        passlable = new javax.swing.JLabel();
        fpass = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Your Data");

        idlable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        idlable.setForeground(new java.awt.Color(0, 153, 204));
        idlable.setText("ID");

        namelable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        namelable.setForeground(new java.awt.Color(0, 153, 204));
        namelable.setText("New Name");

        fName.addActionListener(this::fNameActionPerformed);

        passlable.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        passlable.setForeground(new java.awt.Color(0, 153, 204));
        passlable.setText("New Password");

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fpass, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(idlable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fid)
                                .addComponent(namelable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(fName)
                                .addComponent(passlable, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(btnUpdate)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(idlable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(namelable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passlable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnUpdate)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        try {
            String sid = fid.getText();
            if (!sid.matches("\\d+")) {
                throw new IllegalArgumentException("ID must be contain only numbers");
            }
            String name = fName.getText();
            if (!name.matches("^[a-zA-Z][a-zA-Z]*$")) {
                throw new IllegalArgumentException("Name must be contain only letters");
            }
            String passWord = fpass.getText();
            if ((passWord + "").isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please, Enter Password");
            } else {
                updateEmployee(Integer.parseInt(sid), name, passWord);
            }
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Input Error", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Update_Employee_info().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTextField fName;
    private javax.swing.JTextField fid;
    private javax.swing.JTextField fpass;
    private javax.swing.JLabel idlable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel namelable;
    private javax.swing.JLabel passlable;
    // End of variables declaration//GEN-END:variables
public void updateEmployee(int id, String newName, String newPass) {
        String fileName = "employee.txt";
        File file = new File(fileName);

        if (!file.exists()) {
            JOptionPane.showMessageDialog(this,
                    "file not found",
                    "File Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Scanner sc = new Scanner(file);
            StringBuilder newContent = new StringBuilder();
            boolean found = false;

            while (sc.hasNextLine()) {
                String line = sc.nextLine().trim();
                if (line.isEmpty()) {
                    continue;
                }

                String[] parts = line.split(",");

                int currentId = Integer.parseInt(parts[0].trim());

                if (currentId == id) {
                    String updatedLine = id + "," + newName + "," + newPass;
                    newContent.append(updatedLine).append("\n");
                    found = true;
                } else {
                    newContent.append(line).append("\n");
                }
            }
            sc.close();
            if (!found) {
                JOptionPane.showMessageDialog(this,
                        "ID not foud",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            java.io.FileWriter writer = new java.io.FileWriter(file);
            writer.write(newContent.toString());
            writer.close();

            JOptionPane.showMessageDialog(this,
                    "Done Successfully",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error During read file",
                    "File Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

}
